Imports System.Drawing.Printing

Public Class QRcode
    Private Sub Detail_BeforePrint(sender As Object, e As PrintEventArgs) Handles Detail.BeforePrint
        XrLabel1.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode1.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel2.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode2.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel3.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode3.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel4.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode4.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel5.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode5.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel6.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode6.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel7.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode7.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel8.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode8.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel9.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode9.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel10.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode10.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel11.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode11.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel12.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode12.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel13.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode13.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel14.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode14.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel15.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode15.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel16.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode16.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel17.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode17.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel18.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode18.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel19.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode19.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel20.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode20.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel21.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode21.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel22.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode22.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel23.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode23.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel24.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode24.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel25.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode25.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel26.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode26.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel27.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode27.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel28.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode28.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel29.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode29.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel30.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode30.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel31.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode31.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel32.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode32.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel33.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode33.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel34.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode34.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel35.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode35.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel36.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode36.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel37.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode37.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel38.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode38.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel39.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode39.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel40.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode40.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel41.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode41.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel42.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode42.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel43.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode43.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel44.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode44.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel45.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode45.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel46.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode46.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel47.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode47.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel48.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode48.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel49.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode49.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel50.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode50.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel51.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode51.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel52.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode52.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel53.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode53.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel54.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode54.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel55.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode55.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
        XrLabel56.Text = frmMain.Art & "-" & frmQRcode.Id & "-" & frmQRcode.Sex & "-" & frmQRcode.Age
        XrBarCode56.Text = frmMain.Art & frmQRcode.Id & frmQRcode.Sex & frmQRcode.Age
    End Sub
End Class